<?php
	include("header.php");
	
?>
<html>
	<head>
		<title>History</title>
		<link rel="stylesheet" href="css.css"/>											<!--External CSS-->
		
		<meta name="viewport" content="width=device-width, initial-scale=1">			<!--Offline Bootstrap-->
		<link rel="stylesheet" href="css\bootstrap.min.css"/>
		<script src="js\jquery.min.js"></script>
		<script src="js\bootstrap.min.js"></script>
	</head>
	<body>
	<div class="container-fluid">
		<div class="row">
		<br><br><br><br><br><br><br><br><br><br><br><br><br>
			<div class="col-sm-1"></div>
			<div class="col-sm-10 data">
				<p>Maharashtra was ruled by the Maurya Empire in the 4th and 3rd centuries BCE. Around 230 BCE Maharashtra came under the rule of the Satavahana dynasty for 400 years. The greatest ruler of the Satavahana Dynasty was Gautamiputra Satakarni. In 90 CE Vedishri, son of the Satavahana king Satakarni, the "Lord of Dakshinapatha, wielder of the unchecked wheel of Sovereignty", made Junnar, thirty miles north of Pune, the capital of his kingdom. The state was also ruled by Western Satraps, Gupta Empire, Gurjara-Pratihara, Vakataka, Kadambas, Chalukya Empire, Rashtrakuta Dynasty, and Western Chalukya before finally, the Yadava rule. The Buddhist Ajanta Caves in present-day Aurangabad display influences from the Satavahana and Vakataka style. The caves were possibly excavated during this period.The Chalukya dynasty ruled from the 6th century to the 8th century CE and the two prominent rulers were Pulakeshin II, who defeated the north Indian Emperor Harsha, and Vikramaditya II, who defeated the Arab invaders in the 8th century. The Rashtrakuta dynasty ruled Maharashtra from the 8th to the 10th century. The Arab traveller Sulaiman described the ruler of the Rashtrakuta Dynasty (Amoghavarsha) as "one of the 4 great kings of the world". Shilahara Dynasty began as vassals of the Rashtrakuta dynasty which ruled the Deccan plateau between the 8th and 10th centuries. From the early 11th century to the 12th century the Deccan Plateau, which includes a significant part of Maharashtra, was dominated by the Western Chalukya Empire and the Chola dynasty. Several battles were fought between the Western Chalukya Empire and the Chola dynasty in the Deccan Plateau during the reigns of Raja Raja Chola I, Rajendra Chola I, Jayasimha II, Someshvara I and Vikramaditya VI.</p>
				<p>In the early 14th century, the Yadava dynasty, which ruled most of present-day Maharashtra, was overthrown by the Delhi Sultanate ruler Ala-ud-din Khalji. Later, Muhammad bin Tughluq conquered parts of the Deccan, and temporarily shifted his capital from Delhi to Daulatabad in Maharashtra. After the collapse of the Tughluqs in 1347, the local Bahmani Sultanate of Gulbarga took over, governing the region for the next 150 years. After the break-up of the Bahamani sultanate in 1518, Maharashtra split into five Deccan Sultanates: Nizamshah of Ahmednagar, Adilshah of Bijapur, Qutubshah of Golkonda, Bidarshah of Bidar and Imadshah of Elichpur. These kingdoms often fought with each other. United, they decisively defeated the Vijayanagara Empire of the south in 1565.The present area of Mumbai was ruled by the Sultanate of Gujarat before its capture by Portugal in 1535 and the Faruqi dynasty ruled the Khandesh region between 1382 and 1601 before finally getting annexed by the Mughal Empire. Malik Ambar, the regent of the Nizamshahi dynasty of Ahmednagar from 1607 to 1626.increased the strength and power of Murtaza Nizam Shah and raised a large army. Malik Ambar is said to have been a proponent of guerilla warfare in the Deccan region. Malik Ambar assisted Mughal emperor Shah Jahan in Delhi against his stepmother, Nur Jahan, who had ambitions of seating her son-in-law on the throne.</p>
				<p>By the early 17th century, Shahaji Bhosale, an ambitious local general who had served Ahmadnagar Nizamshahi, the Mughals and Adil Shah of Bijapur at different periods during his career, attempted to establish his independent rule.His son Shivaji Maharaj succeeded in establishing the Maratha Empire which was further expanded during the 18th century by the Bhat family Peshwas based in Pune, Bhonsle of Nagpur, Gaekwad of Baroda, Holkar of Indore, Scindia of Gwalior.At its peak, the empire covered much of the subcontinent, encompassing a territory of over 2.8 million km². The Marathas are credited to a large extent for ending the Mughal rule in India.The Marathas defeated the Mughals, and conquered large territories in northern and central parts of the Indian subcontinent. After their defeat at the hand of Ahmad Shah Abdali's Afghan forces in the Third Battle of Panipat in 1761, the Maratha suffered a setback. However, the Marathas soon regained lost influence and ruled central and north India including New Delhi until the end of the eighteenth century. The Third Anglo-Maratha War (1817–1818) led to the end of the Maratha Empire and East India Company ruled the country in 1819.[38][39] The Marathas also developed a potent Navy circa 1660s, which at its peak, dominated the territorial waters of the western coast of India from Mumbai to Savantwadi.It would engage in attacking the British, Portuguese, Dutch, and Siddi Naval ships and kept a check on their naval ambitions. The Maratha Navy dominated till around the 1730s, was in a state of decline by 1770s, and ceased to exist by 1818.</p>
				<p>India contains no more than two great powers, British and Mahratta, and every other state acknowledges the influence of one or the other. Every inch that we recede will be occupied by them.<p>
				<p>The British governed western Maharashtra as part of the Bombay Presidency, which spanned an area from Karachi in Pakistan to northern Deccan. A number of the Maratha states persisted as princely states, retaining autonomy in return for acknowledging British suzerainty. The largest princely states in the territory were Nagpur, Satara and Kolhapur; Satara was annexed to the Bombay Presidency in 1848, and Nagpur was annexed in 1853 to become Nagpur Province, later part of the Central Provinces. Berar, which had been part of the Nizam of Hyderabad's kingdom, was occupied by the British in 1853 and annexed to the Central Provinces in 1903.However, a large part called Marathwada remained part of the Nizam's Hyderabad State throughout the British period.</p>
				<p>The period of British rule was marked by social reforms and an improvement in infrastructure as well as revolts due to their discriminatory policies. At the turn of the 20th century, the struggle for independence took shape, led by radical nationalist Bal Gangadhar Tilak and the moderates like Justice Mahadev Govind Ranade, Gopal Krishna Gokhale, Pherozeshah Mehta and Dadabhai Naoroji, Dr. B. R. Ambedkar, Jyotirao Phule - social reformers who were all born in this region. Tilak was an inspiration to many Nationalists from the following generation like Vinayak Damodar Savarkar. After the partial autonomy given to the states by the Government of India Act of 1935, B. G. Kher became the first Chief Minister of the Congress party led Government of tri-lingual Bombay Presidency.The ultimatum to the British during the Quit India Movement was given in Mumbai, and culminated in the transfer of power and independence in 1947.</p>
				<p>After India's independence, the Deccan States, including Kolhapur were integrated into Bombay State, which was created from the former Bombay Presidency in 1950.In 1956, the States Reorganisation Act reorganised the Indian states along linguistic lines, and Bombay Presidency State was enlarged by the addition of the predominantly Marathi-speaking regions of Marathwada (Aurangabad Division) from erstwhile Hyderabad state and Vidarbha region from the Central Provinces and Berar. The southernmost part of Bombay State was ceded to Mysore. From 1954 to 1955 the people of Maharashtra strongly protested against bilingual Bombay state and Samyukta Maharashtra Samiti, was formed.The Mahagujarat Movement was started, seeking a separate Gujarat state. Keshavrao Jedhe, S.M. Joshi, Shripad Amrit Dange, Pralhad Keshav Atre and Gopalrao Khedkar fought for a separate state of Maharashtra with Mumbai as its capital under the banner of Samyukta Maharashtra Movement. On 1 May 1960, following mass protests and 105 deaths, the separate Marathi-speaking state was formed by dividing earlier Bombay State into the new states of Maharashtra and Gujarat.The state continues to have a dispute with Karnataka regarding the region of Belgaum and Karwar.</p>
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
	</body>
</html>